name: Install CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true

      - name: Install via webscript (Windows)
        if: runner.os == 'Windows'
        run: curl -o install.vsh https://raw.githubusercontent.com/vlang/v-analyzer/main/install.vsh; v run install.vsh; del install.vsh

      - name: Install via webscript (nix)
        if: runner.os != 'Windows'
        run: v -e "$(curl https://raw.githubusercontent.com/vlang/v-analyzer/main/install.vsh -fsSL)"

      - name: Verify installation success
        run: ~/.config/v-analyzer/bin/v-analyzer --version

      - name: Checkout v-analyzer
        uses: actions/checkout@v4

      - name: Cleanup and prepare installation
        shell: bash
        run: |
          rm -r ~/.config/v-analyzer/bin/v-analyzer
          mkdir Downloads
          mv ./install.vsh Downloads/install.vsh

        # While the webscript installation step tests the general functionality of direct installation via the web,
        # regressions related to the install script would only become visible AFTER pushing changes to the main branch.
        # We reduce the potential for errors by simulating downloading the script and running it separately.
      - name: Install via local script
        run: cd Downloads && v run install.vsh

      - name: Verify installation success
        run: ~/.config/v-analyzer/bin/v-analyzer --version
