name: Tree-sitter CI

on:
  push:
    paths:
      - 'tree_sitter_v/**'
  pull_request:
    paths:
      - 'tree_sitter_v/**'

jobs:
  test:
    name: Test tree-sitter
    runs-on: ubuntu-latest

    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout v-analyzer
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd tree_sitter_v && npm update

      - name: Run tests
        run: cd tree_sitter_v && npm run test
